// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsApp.DataAccess;

#nullable disable

namespace WinFormsApp.Migrations
{
    [DbContext(typeof(WinFormsContext))]
    [Migration("20240403150108_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WinFormsApp.DataAccess.ClassModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(351),
                            Name = "One"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(373),
                            Name = "Two"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(377),
                            Name = "Three"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(385),
                            Name = "Four"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(388),
                            Name = "Five"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(391),
                            Name = "Six"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(395),
                            Name = "Seven"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(399),
                            Name = "Eight"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(402),
                            Name = "Nine"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(406),
                            Name = "Ten"
                        });
                });

            modelBuilder.Entity("WinFormsApp.DataAccess.StudentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5fd4d018-805f-400e-8d60-6c38cf97c462"),
                            ClassId = 1,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(1070),
                            DOB = new DateTime(2010, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 1,
                            Name = "John"
                        },
                        new
                        {
                            Id = new Guid("d07eac83-6ec5-4af9-ae2b-6f26a6c3223d"),
                            ClassId = 7,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(1086),
                            DOB = new DateTime(2012, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 1,
                            Name = "Jamie"
                        },
                        new
                        {
                            Id = new Guid("6ed43c26-c94d-414f-b4b4-c2e6eaa52d57"),
                            ClassId = 5,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(1099),
                            DOB = new DateTime(2015, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 1,
                            Name = "Aaron"
                        },
                        new
                        {
                            Id = new Guid("ac37cbf6-d842-4ef6-ba73-5cb9739a4219"),
                            ClassId = 4,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(1107),
                            DOB = new DateTime(2018, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 2,
                            Name = "Aysha"
                        },
                        new
                        {
                            Id = new Guid("d8cb8acf-8e1b-4d1b-b8a3-f9e966a55b0f"),
                            ClassId = 6,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(1120),
                            DOB = new DateTime(2020, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 1,
                            Name = "Finch"
                        },
                        new
                        {
                            Id = new Guid("1faedb18-a873-4529-8c06-3a0b61d3a1ae"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(1133),
                            DOB = new DateTime(2014, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 1,
                            Name = "Xander"
                        },
                        new
                        {
                            Id = new Guid("e9a39d81-a58a-43fc-acb3-cc870791910b"),
                            ClassId = 2,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(1160),
                            DOB = new DateTime(2014, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 2,
                            Name = "Patricia"
                        },
                        new
                        {
                            Id = new Guid("85e9fd7f-f827-404d-aad4-845c69c7e23f"),
                            ClassId = 4,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(1172),
                            DOB = new DateTime(2012, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 2,
                            Name = "Jane"
                        },
                        new
                        {
                            Id = new Guid("f4eee102-d6a5-46ae-969c-c2bb4b096c76"),
                            ClassId = 5,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(1184),
                            DOB = new DateTime(2014, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 2,
                            Name = "Maria"
                        },
                        new
                        {
                            Id = new Guid("5a446c50-89f3-466b-bba7-e65195eda4b4"),
                            ClassId = 8,
                            CreatedDate = new DateTime(2024, 4, 3, 21, 1, 8, 360, DateTimeKind.Local).AddTicks(1192),
                            DOB = new DateTime(2016, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender = 2,
                            Name = "Kayla"
                        });
                });

            modelBuilder.Entity("WinFormsApp.DataAccess.StudentModel", b =>
                {
                    b.HasOne("WinFormsApp.DataAccess.ClassModel", "ClassModel")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassModel");
                });
#pragma warning restore 612, 618
        }
    }
}
